## Introduction
### Motif-Only Matrix Profile (MOMP): A Faster Approach to Motif Discovery in Time Series
#### *By Joey Higgins*

In this tutorial, we will walk through the Motif-Only Matrix Profile (MOMP), an advanced technique for time series motif discovery, as proposed in the [Motif Only Matrix Profile](https://www.dropbox.com/scl/fi/mt8vp7mdirng04v6llx6y/MOMP_DeskTop.pdf?rlkey=gt6u0egagurkmmqh2ga2ccz85&e=1&dl=0) (Keogh, 2024). MOMP combines the computational efficiency of downsampling with lower-bound approximations, pruning irrelevant subsequences, and refining best motif candidates. This results in a significant speedup compared to traditional Matrix Profile algorithms.

Ultimately, we will walk through the MOMP algorithm with enhancements such as the K-Triangular Inequality Profile (KTIP) and multiresolution pruning. We will also test the performance of MOMP on real-world datasets and compare it with other matrix profile algorithms like STOMP.

### Objectives:
1. Understand how to compute the Lower Bound Matrix Profile (lbMP) and KTIP for aggressive pruning.
2. Implement multiresolution pruning to refine motif search from coarse to fine resolution.
3. Refine the best-so-far (bsf) motif distance with exact distance calculations and cohort point adjustments.
4. Run performance comparisons on real-world datasets.

## Table of Contents

1. [Introduction](#introduction)
2. [Definitions](#definitions)
3. [MOMP Algorithm Overview](#momp-algorithm-overview)
4. [Key Steps in MOMP](#key-steps-in-momp)
   - [Step 1: Downsampling](#step-1-downsampling)
   - [Step 2: Lower Bound Matrix Profile (lbMP) and KTIP](#step-2-lower-bound-matrix-profile-and-ktip)
   - [Step 3: Multiresolution Pruning](#step-3-multiresolution-pruning)
   - [Step 4: Refining the Best-So-Far (bsf) Motif](#step-4-refining-the-best-so-far-motif)
   - [Step 5: Final Exact Matrix Profile Calculation](#step-5-final-exact-matrix-profile-calculation)
5. [Performance Comparisons](#performance-comparisons)
6. [Real-World Dataset Testing](#real-world-dataset-testing)
7. [Conclusion](#conclusion)
8. [References](#references)

#### Getting Started
Importing all required packages

In [2]:
import pandas as pd
import numpy as np
import stumpy
import math

np.set_printoptions(linewidth=100)

## MOMP Algorithm Overview

Motif-Only Matrix Profile (MOMP) improves traditional motif discovery by aggressively pruning subsequences using the **Lower Bound Matrix Profile (lbMP)** and the **K-Triangular Inequality Profile (KTIP)**. Starting with a coarse downsampling rate, the algorithm performs multiresolution pruning, gradually refining the motif search and recalculating the exact matrix profile for unpruned subsequences at the final stage.

### Key Enhancements:
- **Lower Bound Matrix Profile (lbMP)**: The lbMP stores rough estimates of subsequence distances, allowing for pruning.
- **K-Triangular Inequality Profile (KTIP)**: KTIP leverages the triangular inequality to refine subsequence distance estimates and prune unpromising pairs.
- **Multiresolution Pruning**: The motif search begins with coarse approximations and progressively increases resolution to focus on promising subsequences.
- **Cohort Points**: These are anchor points used in the final motif refinement stage to ensure local subsequences are correctly aligned.

## Definitions

Before we dive into the implementation, let’s define some key terms that will help you understand the MOMP process:

- **Best-So-Far (bsf)**: The smallest distance between any two subsequences that has been found so far. As the algorithm progresses, the bsf is updated whenever a smaller distance is discovered.
- **Cohort Points**: Cohort points are the anchor subsequences that help refine the best-so-far (bsf) motif distance during the final stages of the algorithm.
- **Downsampling**: The process of reducing the resolution of the time series by averaging over groups of data points. Downsampling speeds up initial calculations by working with a coarser representation of the time series.
- **dsr**: Downsampling Rate, or the factor by which the time series is reduced. For example, a dsr of 2 means that every two points in the original time series are averaged into one point.
- **Lower Bound**: A rough estimate of the minimum possible distance between subsequences, computed using the downsampled time series. Lower bounds are used to quickly prune unpromising subsequences before calculating the exact distance.
- **lbMP**: Lower Bound Matrix Profile, which stores the lower bound distances between subsequences in the time series. It helps in identifying which subsequences can be pruned.
- **Matrix Profile (MP)**: A data structure that stores the z-normalized Euclidean distance between each subsequence in a time series and its nearest neighbor. The MP is used to efficiently identify motifs in the data.
- **Motif**: A repeating pattern in a time series that occurs at least twice. Motifs are subsequences with minimal Euclidean distances between them.
- **Multiresolution Pruning**: This refers to the process of starting the motif search at a coarse downsampling rate, pruning subsequences based on lower bounds, and iteratively refining the search at finer resolutions.
- **Pruning**: The process of eliminating subsequences that cannot possibly be motifs based on their lower bound distance. If the lower bound of a subsequence's distance is already greater than the current bsf, it is pruned.

These concepts are essential for understanding how MOMP works.

### Step 1: Downsampling the Time Series

To start, we reduce the resolution of the time series by averaging groups of points. This allows us to quickly approximate the distances between subsequences.6

### Step 2: Computing Lower Bound Approximation and K-Triangular Inequality Profile (KTIP)

The next step is to calculate the lower bound distances between subsequences in the downsampled time series using the K-Triangular Inequality Profile (KTIP) algorithm. KTIP computes a matrix of lower bound distances at various downsampling rates, leveraging powers of 2 to capture increasingly accurate estimates with minimal computation. These lower bounds help us quickly identify which parts of the time series are likely irrelevant by providing a fast approximation of distances. This allows us to efficiently "prune" or ignore segments that are unlikely to contain the best matches, focusing our search on the most promising regions.

In [3]:
def computeKTIP(T, m, dsr0):
    """
    Compute the K-Triangular Inequality Profile (KTIP).
    
    Parameters:
    - T: Input time series (array-like)
    - m: Subsequence length (integer)
    - dsr0: Initial downsampling rate (integer)
    
    Returns:
    - ktip: Lower bound matrix profile
    """

    n = len(T)
    num_diags = int(math.log2(dsr0)) + 1  # Number of diagonal levels based on dsr0
    ktip = np.full((n - m + 1, num_diags), np.nan)  # Initialize ktip with NaN values
    temp = np.full((n - m + 1), np.inf)  # Initialize temp with infinity values
    
    for diag in range(1, dsr0 + 1):
        for rr in range(n - m - diag + 2):
            cc = rr + diag
            if cc >= len(T) - m + 1:
                break  # Avoids accessing out-of-bounds indices
            dist = np.sqrt(np.sum((T[rr:rr + m] - T[cc:cc + m]) ** 2))
            
            # Update temp for minimum distances
            if dist < temp[rr]:
                temp[rr] = dist

            if dist < temp[cc]:
                temp[cc] = dist
        
        # Store temp values in ktip at log2(diag) positions if diag is a power of 2
        if math.log2(diag).is_integer():
            ktip[:, int(math.log2(diag))] = temp
    
    return ktip

T = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])  # Sample time series
m = 3  # Subsequence length
dsr0 = 4  # Initial downsampling rate

ktip_result = computeKTIP(T, m, dsr0)
print("KTIP Matrix:\n", ktip_result)

# Basic checks
assert ktip_result.shape == (len(T) - m + 1, int(math.log2(dsr0)) + 1), "Output dimensions incorrect."
assert not np.isnan(ktip_result).all(), "All values in the result are NaN."

KTIP Matrix:
 [[1.73205081 1.73205081 1.73205081]
 [1.73205081 1.73205081 1.73205081]
 [1.73205081 1.73205081 1.73205081]
 [1.73205081 1.73205081 1.73205081]
 [1.73205081 1.73205081 1.73205081]
 [1.73205081 1.73205081 1.73205081]
 [1.73205081 1.73205081 1.73205081]
 [1.73205081 1.73205081 1.73205081]]


In [3]:
def test_computeKTIP():


# Run the test
test_computeKTIP()

KTIP Matrix:
 [[1.73205081 1.73205081 1.73205081]
 [1.73205081 1.73205081 1.73205081]
 [1.73205081 1.73205081 1.73205081]
 [1.73205081 1.73205081 1.73205081]
 [1.73205081 1.73205081 1.73205081]
 [1.73205081 1.73205081 1.73205081]
 [1.73205081 1.73205081 1.73205081]
 [1.73205081 1.73205081 1.73205081]]
Test passed: KTIP matrix dimensions and basic values are valid.


### Step 3: Pruning Irrelevant Data

Based on the lower bound distances, we can prune subsequences that are guaranteed not to contain motifs. These subsequences have a lower bound greater than the current best-so-far (bsf) motif distance.

### Step 4: Refining the Best-So-Far (bsf) Motif

After pruning, we refine the best-so-far (bsf) by recalculating the exact distances between the remaining subsequences.

## Implementation

Let's combine all the steps into a single MOMP function. This function will downsample the data, compute the lower bounds, prune subsequences, and refine the best motif.

## Conclusion

In this tutorial, we explored how the Motif-Only Matrix Profile (MOMP) algorithm speeds up motif discovery by using downsampling and lower bounds to prune irrelevant subsequences. This approach makes motif discovery scalable even for very large time series.

## References

Shahcheraghi, Maryam and Keogh, Eamonn et al. (2024) Matrix Profile XXXI: Motif-Only Matrix Profile: Orders of Magnitude Faster. ICDM: TBD. [Link](https://www.dropbox.com/scl/fi/mt8vp7mdirng04v6llx6y/MOMP_DeskTop.pdf?rlkey=gt6u0egagurkmmqh2ga2ccz85&e=1&dl=0)